### ISSUE TITLE
Checklist entity

### ISSUE THREAD

**Issue by Mehonoshin** [ArtemRakov/todo_app#2]
Any user can start a new checklist from given template. Whenever he finds a template that fits his needs, he can click "Use it!" button, and a new checklist will be created for him.

Also, we need an ability to create a new checklist from scratch. From user point of view it should look like he basically creates just a checklist and fills the questions. But under the hood it should also create a template first, and then a checklist model, that is actually used by user. It will allow us to clone existing templates, fork and modify them.

Also, we'd like to keep track of all forks of templates in the database, so we are able to gather the information about modifications of templates across system.

Every time when the user marks an item in checklist as "done", we mark ChecklistItem record as done, but not the TemplateChecklistItem.

**Comment by ArtemRakov** [comment]
Насколько я понял то user может найти чужой template и скопировать себе его в checklist. 

Но я не особо понимаю , как создаются template.
1. Я как обычный user создаю checklist и добавляю туда todo ( в нашем случае это item). Как я понимаю template должен копировать эти todo (item) к себе. Я правильно понимаю? Когда я добавляю todo(item) в checklist (то он еще добавляется в template)? 
2. Если все так как в пункте 1. Могу ли я изменять template, не касаясь checklist? То есть добавлять item. Не через checklist.
3. Не проще и удобнее иметь кнопку например "Create template from this checklist". Которая копирует все item в template?

**Comment by Mehonoshin** [comment]
Нет, template это уже готовый набор задач в рамках одного листа. Каждый юзер может создать N чеклистов из шаблона, допустим он может создать чеклист и назначить его на определенные даты. 
Например, я создаю template уборки дома. Я добавляю в него 3 пункта:
1. Вытереть пыль
2. Пропылесосить
3. Помыть полы

После чего я могу либо прямо сейчас заюзать его, создав чеклист из шаблона. Либо могу сделать его повторяющимся, допустим каждый четверг система будет напоминать что что я должен выполнить этот чеклист.

**Comment by Mehonoshin** [comment]
Грубо говоря связи в моделях должны быть примерно такими

ChecklistTemplate has_many TemplateItems
Checklist belongs_to ChecklistTemplate
TemplateItem has_many ItemUsages, class_name: 'Item'
Item belongs_to checklist
Item belongs_to TemplateItem

**Comment by Mehonoshin** [comment]
Не думай пока как это будет выглядеть для юзера, на данном этапе нам нужно правильно спланировать модель данных, а в интерфейсе всегда можно преподнести это как юзеру будет понятнее.
