### ISSUE TITLE
Setup CD

### ISSUE THREAD

**Issue by Mehonoshin** [ArtemRakov/todo_app#24]
Let's deploy from CI to heroku whenever master build is green

**Comment by ArtemRakov** [comment]
Все правильно?
<img width="1216" alt="Снимок экрана 2019-05-04 в 15 34 57" src="https://user-images.githubusercontent.com/26395360/57179058-35448e80-6e82-11e9-8397-b863ce88e6a1.png">

**Comment by Mehonoshin** [comment]
можно и так) только галочку поставь чтобы дожидалось завершения CI перед депллоем
