### ISSUE TITLE
Inherited and Custom Items

### ISSUE THREAD

**Issue by Mehonoshin** [ArtemRakov/todo_app#39]
STI

**Comment by ArtemRakov** [comment]
```ruby
class BaseItem < ApplicationRecord

end```

```ruby
class TemplateItem < BaseItem
belongs_to :checklist_template
end
```

```ruby 
class ChecklistItem < BaseItem
belongs_to :checklist

```

I think this will lead to null values e.g TemplateItem instance will have checklist equal to null and ChecklistItem will have checklist_template item eqaul to null. Is this behavior that we want?
