### ISSUE TITLE
Item title field

### ISSUE THREAD

**Issue by ArtemRakov** [ArtemRakov/todo_app#5]
В данный момент
У Item имеет только один field. done boolean. 
Item ссылается на TemplateItem. Откуда берет title.

<img width="692" alt="Снимок экрана 2019-04-29 в 0 07 20" src="https://user-images.githubusercontent.com/26395360/56870106-e8406280-6a12-11e9-972f-454d82c6a262.png">

Мне кажется, в Item должен был field title. Просто тогда пользователь не сможет изменить название Item в Checklist, не меняя TemplateItem. 

**show.html.erb**
<img width="580" alt="Снимок экрана 2019-04-29 в 0 11 20" src="https://user-images.githubusercontent.com/26395360/56870137-64d34100-6a13-11e9-9958-ba4a6014a468.png">

**item.rb**
<img width="432" alt="Снимок экрана 2019-04-29 в 0 12 25" src="https://user-images.githubusercontent.com/26395360/56870148-7f0d1f00-6a13-11e9-94a6-ac6df19ed5c4.png">

то есть когда кто-то решил изменить TemplateItem в ChecklisTemplate то наш Item тоже изменит название.

**Comment by ArtemRakov** [comment]
PR: https://github.com/ArtemRakov/todo_app/pull/4

**Comment by Mehonoshin** [comment]
makes sense, получается изначально названия задач у нас лежат в айтемах шаблона, а в момент создания чеклиста они копируются в айтемы чеклиста, и там мы их уже можем менять.
