### ISSUE TITLE
Объединить controller

### ISSUE THREAD

**Issue by ArtemRakov** [ArtemRakov/todo_app#8]
TemplateItem и Item контроллеры очень похожи, практически идентичны. Тоже самое можно сказать и про ChecklistTemplate и Checklist контроллеры. 

Может создать общий контроллер для TemplateItem и Item. и общий контроллер для ChecklistTemplate и Checklist.

Стоит это делать ? И если стоит то как их назвать (имя общего контроллера) 

PR: https://github.com/ArtemRakov/todo_app/pull/4

**Comment by Mehonoshin** [comment]
я думаю пока что не надо, есть ощущение что скоро они будут различаться
